In [34]:
import pandas as pd
import numpy as np
from scipy import stats
import sys
print(sys.version)

3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]


In [35]:
from imblearn.over_sampling import SMOTE

def smoteOverSamling(train,nn,r):
    sm = SMOTE(random_state=42, k_neighbors = nn, ratio = r)
    return sm.fit_sample(train.drop('fraud',axis=1), train['fraud'])


In [36]:

def my_custom_loss_func(y_true, y_pred):
    cm = confusion_matrix(y_true,y_pred)
    print(cm)
    tn, fp, fn, tp = cm.ravel()
    score = ((-25)*fp + (-5)*fn + 5*tp) / len(y_true)
    return (score)

In [37]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import FunctionTransformer




from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import FunctionTransformer

def normalization(train):
    feature_scaler = StandardScaler()
    X_scaled = pd.DataFrame(feature_scaler.fit_transform(train.values), columns=train.columns, index=train.index)
    return X_scaled


In [38]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix



train_pure=pd.read_csv('train.csv',sep=',',index_col=0)
x_pure= train_pure.drop('fraud',axis=1)
y_pure= train_pure['fraud']

x_train, x_holdout, y_train, y_holdout = train_test_split(x_pure, y_pure, test_size=0.2, random_state=324)

train=x_train
train['fraud']= y_train


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()


In [48]:
x, y =   smoteOverSamling(train,1,0.3)
x_val, y_val = x_holdout, y_holdout

In [49]:

# Logistic Regression
model = Sequential()
model.add(Dense(1, activation='sigmoid', input_dim=x.shape[1]))
model.compile(optimizer='rmsprop', loss='binary_crossentropy')
model.fit(x, y, nb_epoch=10, validation_data=(x_val, y_val))

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:6: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Train on 1851 samples, validate on 376 samples
Epoch 1/10
1851/1851 [==============================] - 1s 415us/step - loss: 11.4166 - val_loss: 13.6642
Epoch 2/10
1851/1851 [==============================] - 0s 27us/step - loss: 11.1984 - val_loss: 13.3728
Epoch 3/10
1851/1851 [==============================] - 0s 25us/step - loss: 10.8923 - val_loss: 12.8600
Epoch 4/10
1851/1851 [==============================] - 0s 25us/step - loss: 10.5119 - val_loss: 12.0741
Epoch 5/10
1851/1851 [==============================] - 0s 33us/step - loss: 9.6957 - val_loss: 10.6280
Epoch 6/10
1851/1851 [==============================] - 0s 24us/step - loss: 7.9812 - val_loss: 7.0813
Epoch 7/10
1851/1851 [==============================] - 0s 25us/step - loss: 4.2834 - val_loss: 1.3216
Epoch 8/10
1851/1851 [==============================] - 0s 24us/step - loss: 3.3359 - val_loss: 1.7773
Epoch 9/10
1851/1851 [==============================] - 0s 23us/step - loss: 3.2376 - val_loss: 1.3505
Epoch 10/10
1851

In [50]:
y_pred = model.predict(x_holdout).astype(int)
my_custom_loss_func(y_holdout,y_pred)


[[351   0]
 [ 25   0]]


-0.3324468085106383

In [51]:
from keras.regularizers import l1_l2
reg = l1_l2(l1=0.01, l2=0.01)

model = Sequential()
model.add(Dense(1, activation='sigmoid', W_regularizer=reg, input_dim=x.shape[1]))
model.compile(optimizer='rmsprop', loss='binary_crossentropy')
model.fit(x, y, nb_epoch=100,  batch_size=1000,validation_data=(x_val, y_val))


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", input_dim=20, kernel_regularizer=<keras.reg...)`
  """
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:7: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  import sys


Train on 1851 samples, validate on 376 samples
Epoch 1/100
1851/1851 [==============================] - 1s 410us/step - loss: 4.3372 - val_loss: 1.6655
Epoch 2/100
1851/1851 [==============================] - 0s 3us/step - loss: 4.3222 - val_loss: 1.6517
Epoch 3/100
1851/1851 [==============================] - 0s 4us/step - loss: 4.3114 - val_loss: 1.6417
Epoch 4/100
1851/1851 [==============================] - 0s 3us/step - loss: 4.3026 - val_loss: 1.6315
Epoch 5/100
1851/1851 [==============================] - 0s 2us/step - loss: 4.2938 - val_loss: 1.6201
Epoch 6/100
1851/1851 [==============================] - 0s 2us/step - loss: 4.2826 - val_loss: 1.6104
Epoch 7/100
1851/1851 [==============================] - 0s 2us/step - loss: 4.2726 - val_loss: 1.6016
Epoch 8/100
1851/1851 [==============================] - 0s 3us/step - loss: 4.2638 - val_loss: 1.5937
Epoch 9/100
1851/1851 [==============================] - 0s 3us/step - loss: 4.2549 - val_loss: 1.5861
Epoch 10/100
1851/1851 [

1851/1851 [==============================] - 0s 3us/step - loss: 3.8821 - val_loss: 1.3488
Epoch 80/100
1851/1851 [==============================] - 0s 3us/step - loss: 3.8798 - val_loss: 1.3474
Epoch 81/100
1851/1851 [==============================] - 0s 3us/step - loss: 3.8778 - val_loss: 1.3461
Epoch 82/100
1851/1851 [==============================] - 0s 3us/step - loss: 3.8756 - val_loss: 1.3426
Epoch 83/100
1851/1851 [==============================] - 0s 3us/step - loss: 3.8735 - val_loss: 1.3406
Epoch 84/100
1851/1851 [==============================] - 0s 3us/step - loss: 3.8714 - val_loss: 1.3386
Epoch 85/100
1851/1851 [==============================] - 0s 2us/step - loss: 3.8695 - val_loss: 1.3363
Epoch 86/100
1851/1851 [==============================] - 0s 2us/step - loss: 3.8676 - val_loss: 1.3343
Epoch 87/100
1851/1851 [==============================] - 0s 2us/step - loss: 3.8659 - val_loss: 1.3322
Epoch 88/100
1851/1851 [==============================] - 0s 2us/step - loss:

In [52]:
y_pred = model.predict(x_holdout).astype(int)
my_custom_loss_func(y_holdout,y_pred)

[[347   4]
 [ 24   1]]


-0.5718085106382979

In [59]:
from keras.layers import Dense, Dropout,Activation,BatchNormalization




hidden_par=7
input_dim= x.shape[1]

model = Sequential()
model.add(Dense(hidden_par, input_dim=input_dim, init='uniform',
                W_regularizer=reg,
                bias_regularizer=reg
               ))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(1, activation='sigmoid', input_dim=(hidden_par,),
               W_regularizer=reg,
                bias_regularizer=reg))
model.compile(optimizer='rmsprop', loss='binary_crossentropy')

model.fit(x, y, nb_epoch=100,batch_size=1000, validation_data=(x_val, y_val))

model.summary()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, input_dim=20, bias_regularizer=<keras.reg..., kernel_initializer="uniform", kernel_regularizer=<keras.reg...)`
  if sys.path[0] == '':
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:20: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", input_dim=(7,), bias_regularizer=<keras.reg..., kernel_regularizer=<keras.reg...)`
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:23: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Train on 1851 samples, validate on 376 samples
Epoch 1/100
1851/1851 [==============================] - 1s 661us/step - loss: 1.2610 - val_loss: 1.3605
Epoch 2/100
1851/1851 [==============================] - 0s 4us/step - loss: 1.2270 - val_loss: 1.2560
Epoch 3/100
1851/1851 [==============================] - 0s 4us/step - loss: 1.1522 - val_loss: 1.1846
Epoch 4/100
1851/1851 [==============================] - 0s 3us/step - loss: 1.1157 - val_loss: 1.1177
Epoch 5/100
1851/1851 [==============================] - 0s 3us/step - loss: 1.0696 - val_loss: 1.0860
Epoch 6/100
1851/1851 [==============================] - 0s 4us/step - loss: 1.0006 - val_loss: 1.0615
Epoch 7/100
1851/1851 [==============================] - 0s 3us/step - loss: 1.0063 - val_loss: 1.0425
Epoch 8/100
1851/1851 [==============================] - 0s 4us/step - loss: 0.9412 - val_loss: 1.0245
Epoch 9/100
1851/1851 [==============================] - 0s 3us/step - loss: 0.9291 - val_loss: 1.0202
Epoch 10/100
1851/1851 [

1851/1851 [==============================] - 0s 3us/step - loss: 0.6304 - val_loss: 0.4499
Epoch 80/100
1851/1851 [==============================] - 0s 4us/step - loss: 0.6450 - val_loss: 0.5842
Epoch 81/100
1851/1851 [==============================] - 0s 4us/step - loss: 0.6373 - val_loss: 0.6214
Epoch 82/100
1851/1851 [==============================] - 0s 4us/step - loss: 0.6277 - val_loss: 0.5957
Epoch 83/100
1851/1851 [==============================] - 0s 3us/step - loss: 0.6236 - val_loss: 0.6240
Epoch 84/100
1851/1851 [==============================] - 0s 3us/step - loss: 0.6155 - val_loss: 0.6516
Epoch 85/100
1851/1851 [==============================] - 0s 3us/step - loss: 0.6215 - val_loss: 0.7057
Epoch 86/100
1851/1851 [==============================] - 0s 3us/step - loss: 0.5949 - val_loss: 0.5922
Epoch 87/100
1851/1851 [==============================] - 0s 3us/step - loss: 0.6193 - val_loss: 0.4812
Epoch 88/100
1851/1851 [==============================] - 0s 3us/step - loss:

In [60]:
y_pred = model.predict(x_holdout).astype(int)
my_custom_loss_func(y_holdout,y_pred)

[[351   0]
 [ 25   0]]


-0.3324468085106383